name: Issue Assigner

on: issues

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Auto Assign Issue
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: .github/issue_auto_assign.yml 