name: PR Review Assigner

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Auto Assign Reviewer
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: .github/pr_review_auto_assign.yml 